# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import predict_pb2 as predict_dot_predict__pb2


class StonksPredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predictor = channel.unary_unary(
                '/predictor.StonksPredictor/Predictor',
                request_serializer=predict_dot_predict__pb2.PredictorRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.PredictorResponse.FromString,
                )


class StonksPredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StonksPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predictor': grpc.unary_unary_rpc_method_handler(
                    servicer.Predictor,
                    request_deserializer=predict_dot_predict__pb2.PredictorRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.PredictorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predictor.StonksPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StonksPredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predictor.StonksPredictor/Predictor',
            predict_dot_predict__pb2.PredictorRequest.SerializeToString,
            predict_dot_predict__pb2.PredictorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
