# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict/predict.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15predict/predict.proto\x12\tpredictor\"!\n\x10PredictorRequest\x12\r\n\x05query\x18\x01 \x01(\t\"$\n\x11PredictorResponse\x12\x0f\n\x07numbers\x18\x01 \x03(\x02\x32Y\n\x0fStonksPredictor\x12\x46\n\tPredictor\x12\x1b.predictor.PredictorRequest\x1a\x1c.predictor.PredictorResponseB6Z4github.com/MonoBear123/proto_gen/gen/predict;predictb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict.predict_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/MonoBear123/proto_gen/gen/predict;predict'
  _PREDICTORREQUEST._serialized_start=36
  _PREDICTORREQUEST._serialized_end=69
  _PREDICTORRESPONSE._serialized_start=71
  _PREDICTORRESPONSE._serialized_end=107
  _STONKSPREDICTOR._serialized_start=109
  _STONKSPREDICTOR._serialized_end=198
# @@protoc_insertion_point(module_scope)
